// AUTH
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";


// POSTS
export const SET_POST = "SET_POST";
export const SET_POSTS = "SET_POSTS";
export const LOADING_POST = "LOADING_POST";
export const LOADING_POSTS = "LOADING_POSTS";


// COMMENTS
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";


// USERS
export const UPDATING_USER_INFO = "UPDATING_USER_INFO";
export const FETCH_USER_INFO = "FETCH_USER_INFO";